#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	PLAYER,
	EXPLOSION,
	BACKGROUND,
	BULLET,
	ENEMY,
	POWERUP,
	FINISH_LEVEL,
	ENEMY_BULLET,
	HEART,
	START_BUTTON,
	INSTRUCTIONS_BUTTON,
	QUIT_BUTTON,
	TRY_AGAIN_BUTTON,
	BACK_TO_MENU_BUTTON,
	CONTROLS,
	COIN,
	BOSS,
	NUM_OF_TYPES
};
#endif /* defined (__GAME_OBJECT_TYPE__) */